apiVersion: v1
kind: ServiceAccount
metadata:
  name: mst-mongodb
secrets:
  - name: mst-mongodb

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mst-mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mst-mongodb
subjects:
  - kind: ServiceAccount
    name: mst-mongodb
    namespace: mst

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mst-mongodb
rules:

  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      # - sbt-restricted
      - gce.privileged

  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
