
# docker build . -t eu.gcr.io/ceiba-test-infrastructure/mongodb/mongodb-replicaset:4.2.3
# docker build . -t eu.gcr.io/ceiba-test-infrastructure/mongodb/mongodb-replicaset:4.4.2

# FROM mongo:4.2.3
FROM mongo:4.4.2

WORKDIR /root

ENV MONGODB_ID mongo-0

RUN apt update

COPY /startup-script-mongo /root

CMD ./startup-$MONGODB_ID.sh
